In [1]:
import pandas as pd
import numpy as np
import json

In [3]:
chunk_size = 5000000
index=0
df = pd.read_csv('ProjectTrainingData.csv', nrows=chunk_size, skiprows=index*chunk_size)

In [4]:
def do_sampling(dataframe):
    sample_rate=0.01
    if sample_rate < 1.0:
        np.random.seed(999)
        r1 = np.random.uniform(0, 1, dataframe.shape[0])
        dataframe = dataframe.iloc[r1 < sample_rate,:]
        print ("testing with small sample of training data, ", dataframe.shape)
        return dataframe

df = do_sampling(df)

testing with small sample of training data,  (49905, 24)

In [5]:
df.columns = ['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21']

df.describe()

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,4.990500e+04,49905.000000,4.990500e+04,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000,49905.000000
mean,9.271719e+18,0.171285,1.410214e+07,1004.989540,0.258992,1.021120,0.221381,18522.858671,319.636269,59.059373,2082.732071,1.655445,190.664743,48857.658491,79.986995
std,5.315631e+18,0.376762,4.247125e+01,1.074629,0.471527,0.519493,0.686256,4681.933755,27.591077,46.422902,570.416769,1.362634,314.443947,50041.459266,63.310213
min,1.523000e+14,0.000000,1.410210e+07,1001.000000,0.000000,0.000000,0.000000,375.000000,216.000000,36.000000,112.000000,0.000000,33.000000,-1.000000,13.000000
25%,4.667723e+18,0.000000,1.410211e+07,1005.000000,0.000000,1.000000,0.000000,17163.000000,320.000000,50.000000,1873.000000,0.000000,35.000000,-1.000000,32.000000
50%,9.345456e+18,0.000000,1.410211e+07,1005.000000,0.000000,1.000000,0.000000,19998.000000,320.000000,50.000000,2260.000000,2.000000,39.000000,-1.000000,61.000000
75%,1.389682e+19,0.000000,1.410220e+07,1005.000000,1.000000,1.000000,0.000000,21684.000000,320.000000,50.000000,2496.000000,3.000000,169.000000,100084.000000,111.000000
max,1.844662e+19,1.000000,1.410221e+07,1012.000000,7.000000,5.000000,5.000000,21822.000000,1024.000000,1024.000000,2520.000000,3.000000,1835.000000,100248.000000,221.000000

In [5]:
df.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
37,1.000777e+19,0,14102100,1005,0,85f751fd,c4e18dd6,50e219e0,e2a1ca37,2347f47a,...,1,0,15708,320,50,1722,0,35,-1,79
177,1.003023e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15705,320,50,1722,0,35,100084,79
217,1.003562e+19,0,14102100,1005,0,89a490f5,ce307e01,3e814130,ecad2386,7801e8d9,...,1,0,19771,320,50,2227,0,687,100075,48
333,1.005719e+18,0,14102100,1005,0,f282ab5a,61eb5bc4,f028772b,ecad2386,7801e8d9,...,1,0,20596,320,50,2161,0,35,-1,157
359,1.006040e+19,1,14102100,1005,0,d9750ee7,98572c79,f028772b,ecad2386,7801e8d9,...,1,0,17914,320,50,2043,2,39,-1,32

In [6]:
# check unique values in each column
for col in df.columns:
    print(col, len(df[col].value_counts()))

id 49905
click 2
hour 33
C1 7
banner_pos 6
site_id 1000
site_domain 842
site_category 18
app_id 1000
app_domain 76
app_category 22
device_id 9012
device_ip 40095
device_model 2558
device_type 4
device_conn_type 4
C14 571
C15 7
C16 8
C17 181
C18 4
C19 43
C20 155
C21 38

In [7]:
# check feature distribution
print(df.groupby('site_id')['click'].count().sort_values(ascending=False).head(10))
print(df.groupby('app_id')['click'].count().sort_values(ascending=False).head(10))

site_id
85f751fd    18315
1fbe01fe     8825
e151e245     2372
d9750ee7     1659
5b08c53b      999
856e6d3f      973
5b4d2eda      794
5ee41ff2      500
6399eda6      482
6256f5b4      391
Name: click, dtype: int64
app_id
ecad2386    31590
e2fcccd2     1467
7358e05e     1098
febd1138      953
66f5e02e      837
9c13b419      672
54c5d545      579
a5184c22      545
f0d41ff1      423
03528b27      379
Name: click, dtype: int64

In [8]:
# check out the proportion
print(f"top1 site id: {df[df['site_id'] == '85f751fd'].shape[0] / df.shape[0]}")
print(f"top1 app id: {df[df['app_id'] == 'ecad2386'].shape[0] / df.shape[0]}")

top1 site id: 0.36699729486023447
top1 app id: 0.6330027051397655

In [9]:
print(f" top1 site id count + top1 app id count: {df[df['site_id'] == '1fbe01fe'].shape[0] + df[df['app_id'] == 'ecad2386'].shape[0]}")
print(f" total dataset count: {df.shape[0]}")

# each data is either "site id == 1fbe01fe" or "app_id ==  ecad2386"

 top1 site id count + top1 app id count: 40415
 total dataset count: 49905

In [6]:


def feature_engineering(dataframe):
    
    dataframe = dataframe.drop(['id'], axis=1)
    
    # extract week & hour
    dataframe['Date'] = pd.to_datetime(dataframe['hour'], format='%y%m%d%H')
    dataframe['Day'] = dataframe['Date'].dt.day
    dataframe['Weekday'] = dataframe['Date'].dt.dayofweek
    dataframe['Hour'] = dataframe['Date'].dt.hour
    print(dataframe.head())
    dataframe = dataframe.drop(['Date', 'hour'], axis=1)

    # extract new feature from app id and site id
    dataframe.loc[:, 'is_ecad2386'] = 0
    dataframe.loc[dataframe.app_id=='ecad2386', 'is_ecad2386'] = 1
    print(dataframe.head())
    
    return dataframe
    

df2 = feature_engineering(df)

for col in df2.columns:
    print(col, len(df2[col].value_counts()))

     click      hour    C1  banner_pos   site_id site_domain site_category  \
37       0  14102100  1005           0  85f751fd    c4e18dd6      50e219e0
177      0  14102100  1005           0  1fbe01fe    f3845767      28905ebd
217      0  14102100  1005           0  89a490f5    ce307e01      3e814130
333      0  14102100  1005           0  f282ab5a    61eb5bc4      f028772b
359      1  14102100  1005           0  d9750ee7    98572c79      f028772b

       app_id app_domain app_category  ... C16   C17 C18  C19     C20  C21  \
37   e2a1ca37   2347f47a     8ded1f7a  ...  50  1722   0   35      -1   79
177  ecad2386   7801e8d9     07d7df22  ...  50  1722   0   35  100084   79
217  ecad2386   7801e8d9     07d7df22  ...  50  2227   0  687  100075   48
333  ecad2386   7801e8d9     07d7df22  ...  50  2161   0   35      -1  157
359  ecad2386   7801e8d9     07d7df22  ...  50  2043   2   39      -1   32

          Date  Day  Weekday  Hour
37  2014-10-21   21        1     0
177 2014-10-21   21        1     0
217 2014-10-21   21        1     0
333 2014-10-21   21        1     0
359 2014-10-21   21        1     0

[5 rows x 27 columns]
     click    C1  banner_pos   site_id site_domain site_category    app_id  \
37       0  1005           0  85f751fd    c4e18dd6      50e219e0  e2a1ca37
177      0  1005           0  1fbe01fe    f3845767      28905ebd  ecad2386
217      0  1005           0  89a490f5    ce307e01      3e814130  ecad2386
333      0  1005           0  f282ab5a    61eb5bc4      f028772b  ecad2386
359      1  1005           0  d9750ee7    98572c79      f028772b  ecad2386

    app_domain app_category device_id  ... C16   C17  C18  C19     C20  C21  \
37    2347f47a     8ded1f7a  432cd280  ...  50  1722    0   35      -1   79
177   7801e8d9     07d7df22  a99f214a  ...  50  1722    0   35  100084   79
217   7801e8d9     07d7df22  a99f214a  ...  50  2227    0  687  100075   48
333   7801e8d9     07d7df22  a99f214a  ...  50  2161    0   35      -1  157
359   7801e8d9     07d7df22  a99f214a  ...  50  2043    2   39      -1   32

     Day  Weekday  Hour  is_ecad2386
37    21        1     0            0
177   21        1     0            1
217   21        1     0            1
333   21        1     0            1
359   21        1     0            1

[5 rows x 26 columns]
click 2
C1 7
banner_pos 6
site_id 1000
site_domain 842
site_category 18
app_id 1000
app_domain 76
app_category 22
device_id 9012
device_ip 40095
device_model 2558
device_type 4
device_conn_type 4
C14 571
C15 7
C16 8
C17 181
C18 4
C19 43
C20 155
C21 38
Day 2
Weekday 2
Hour 24
is_ecad2386 2

In [7]:
from sklearn import preprocessing

def feature_encoding(dataframe):
    feats_to_encode = ['C1', 'banner_pos', 'site_id', 'site_domain', 'site_category',
                       'app_id', 'app_domain', 'app_category', 'device_id', 'device_ip', 'device_model',
                      'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'Day', 'Weekday', 'Hour', 'Weekday']
    for column in feats_to_encode:
        enc = preprocessing.LabelEncoder()
        dataframe[column] = enc.fit_transform(dataframe[column])
    
    print(dataframe.info())
    print(dataframe.head())
    
    return dataframe

df3 = feature_encoding(df2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49905 entries, 37 to 4999839
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   click             49905 non-null  int64
 1   C1                49905 non-null  int64
 2   banner_pos        49905 non-null  int64
 3   site_id           49905 non-null  int32
 4   site_domain       49905 non-null  int32
 5   site_category     49905 non-null  int32
 6   app_id            49905 non-null  int32
 7   app_domain        49905 non-null  int32
 8   app_category      49905 non-null  int32
 9   device_id         49905 non-null  int32
 10  device_ip         49905 non-null  int32
 11  device_model      49905 non-null  int32
 12  device_type       49905 non-null  int64
 13  device_conn_type  49905 non-null  int64
 14  C14               49905 non-null  int64
 15  C15               49905 non-null  int64
 16  C16               49905 non-null  int64
 17  C17               49905 non-null  int64
 18  C18               49905 non-null  int64
 19  C19               49905 non-null  int64
 20  C20               49905 non-null  int64
 21  C21               49905 non-null  int64
 22  Day               49905 non-null  int64
 23  Weekday           49905 non-null  int64
 24  Hour              49905 non-null  int64
 25  is_ecad2386       49905 non-null  int64
dtypes: int32(9), int64(17)
memory usage: 8.6 MB
None
     click  C1  banner_pos  site_id  site_domain  site_category  app_id  \
37       0   2           0      525          658              5     889
177      0   2           0      116          798              1     927
217      0   2           0      540          685              3     927
333      0   2           0      939          317             16     927
359      1   2           0      841          505             16     927

     app_domain  app_category  device_id  ...  C16  C17  C18  C19  C20  C21  \
37            9            12       2355  ...    1   39    0    2    0   19
177          34             0       5978  ...    1   39    0    2   61   19
217          34             0       5978  ...    1   89    0   30   54   11
333          34             0       5978  ...    1   82    0    2    0   34
359          34             0       5978  ...    1   74    2    3    0    6

     Day  Weekday  Hour  is_ecad2386
37     0        0     0            0
177    0        0     0            1
217    0        0     0            1
333    0        0     0            1
359    0        0     0            1

[5 rows x 26 columns]

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing


def standardize_data(dataframe):
    scaler = preprocessing.StandardScaler().fit(dataframe)
    dataframe_scaled = scaler.transform(dataframe)
    return pd.DataFrame(dataframe_scaled, columns=dataframe.columns)

def split_data(dataframe):
    x_feats = dataframe.columns[dataframe.columns != 'click']
    X_train = dataframe[x_feats]
    y_train = dataframe['click']

    print(X_train.head())
    print(y_train.head())
    
    X_train = standardize_data(X_train)
    return X_train, y_train


X_train, y_train = split_data(df3)

     C1  banner_pos  site_id  site_domain  site_category  app_id  app_domain  \
37    2           0      525          658              5     889           9
177   2           0      116          798              1     927          34
217   2           0      540          685              3     927          34
333   2           0      939          317             16     927          34
359   2           0      841          505             16     927          34

     app_category  device_id  device_ip  ...  C16  C17  C18  C19  C20  C21  \
37             12       2355      11015  ...    1   39    0    2    0   19
177             0       5978      14317  ...    1   39    0    2   61   19
217             0       5978      27835  ...    1   89    0   30   54   11
333             0       5978       1505  ...    1   82    0    2    0   34
359             0       5978      18520  ...    1   74    2    3    0    6

     Day  Weekday  Hour  is_ecad2386
37     0        0     0            0
177    0        0     0            1
217    0        0     0            1
333    0        0     0            1
359    0        0     0            1

[5 rows x 25 columns]
37     0
177    0
217    0
333    0
359    1
Name: click, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

# Split into train and test data
x_Train, x_Test, y_Train, y_Test = train_test_split(
    X_train, y_train, test_size=0.25, random_state=1, stratify=y_train)

In [13]:
from sklearn.metrics import log_loss,make_scorer

def perform_lr(X_train, y_train, penaltys):
    C_s = [0.01,0.1]
    # C_s = [0.00001,0.0001,0.001, 0.01, 0.1, 1]
    parameters_to_tune = dict(penalty=penaltys, C=C_s)
    model = LogisticRegression(solver='liblinear')
    LogLoss = make_scorer(log_loss, greater_is_better=False, needs_proba=True)
    grid = GridSearchCV(model, parameters_to_tune, cv=5, scoring=LogLoss, verbose=2)
    grid.fit(X_train, y_train)

    print('Best score: ', -grid.best_score_)
    print('Best params: ', grid.best_params_)
    
    return grid

best_grid = perform_lr(X_train, y_train, penaltys = ['l1'])

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .................................C=0.01, penalty=l1; total time=   0.6s
[CV] END .................................C=0.01, penalty=l1; total time=   0.2s
[CV] END .................................C=0.01, penalty=l1; total time=   0.3s
[CV] END .................................C=0.01, penalty=l1; total time=   0.3s
[CV] END .................................C=0.01, penalty=l1; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l1; total time=   0.6s
[CV] END ..................................C=0.1, penalty=l1; total time=   0.3s
[CV] END ..................................C=0.1, penalty=l1; total time=   0.6s
[CV] END ..................................C=0.1, penalty=l1; total time=   0.2s
[CV] END ..................................C=0.1, penalty=l1; total time=   0.1s
Best score:  0.4456105203319879
Best params:  {'C': 0.1, 'penalty': 'l1'}

In [14]:
from sklearn.feature_selection import SelectFromModel

# select feautres with l1 LR

best_l1_model = LogisticRegression(penalty="l1", C=best_grid.best_params_["C"], solver='liblinear')
best_l1_model.fit(X_train, y_train)

select_model = SelectFromModel(best_l1_model,prefit=True)
select_features = select_model.get_support()

feature_names = X_train.columns
feature_names = feature_names[select_features]
X_train = X_train[feature_names]
print(X_train.head())

         C1  banner_pos   site_id  site_domain  site_category  app_domain  \
0 -0.058401   -0.565396  0.223732     0.416103      -0.383792   -1.899123
1 -0.058401   -0.565396 -1.426738     1.103436      -1.064483    0.165596
2 -0.058401   -0.565396  0.284263     0.548660      -0.724137    0.165596
3 -0.058401   -0.565396  1.894380    -1.258045       1.488109    0.165596
4 -0.058401   -0.565396  1.498913    -0.335054       1.488109    0.165596

   app_category  device_ip  device_type  device_conn_type       C14       C15  \
0      1.733309  -0.785491    -0.040656         -0.322595 -1.064314  0.175951
1     -0.499353  -0.498920    -0.040656         -0.322595 -1.081668  0.175951
2     -0.499353   0.674268    -0.040656         -0.322595 -0.352792  0.175951
3     -0.499353  -1.610836    -0.040656         -0.322595  0.179403  0.175951
4     -0.499353  -0.134154    -0.040656         -0.322595 -0.699876  0.175951

        C16       C17       C18       C19       C20      Hour  is_ecad2386
0 -0.176501 -1.158405 -1.214898 -0.620283 -0.838261 -1.460407    -1.313322
1 -0.176501 -1.158405 -1.214898 -0.620283  0.535376 -1.460407     0.761428
2 -0.176501 -0.261078 -1.214898  2.142714  0.377746 -1.460407     0.761428
3 -0.176501 -0.386704 -1.214898 -0.620283 -0.838261 -1.460407     0.761428
4 -0.176501 -0.530276  0.252862 -0.521605 -0.838261 -1.460407     0.761428

In [15]:
# train model with l2 LR to get the final result

best_grid = perform_lr(X_train, y_train, penaltys = ['l2'])

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.2s
Best score:  0.4455090164796854
Best params:  {'C': 0.01, 'penalty': 'l2'}

In [25]:
# Use l2 model and apply it on y test to check logloss value

In [32]:
from sklearn import metrics

lrtest=perform_lr(x_Train,y_Train,penaltys=['l2'])
y_pred=lrtest.predict_proba(x_Test)
log_loss= metrics.log_loss(y_Test,y_pred,eps=1e-15,normalize=True,sample_weight=None, labels=None)
log_loss

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .................................C=0.01, penalty=l2; total time=   0.1s
[CV] END .................................C=0.01, penalty=l2; total time=   0.0s
[CV] END .................................C=0.01, penalty=l2; total time=   0.0s
[CV] END .................................C=0.01, penalty=l2; total time=   0.0s
[CV] END .................................C=0.01, penalty=l2; total time=   0.0s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.0s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.0s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
[CV] END ..................................C=0.1, penalty=l2; total time=   0.1s
Best score:  0.44423229965775174
Best params:  {'C': 0.1, 'penalty': 'l2'}

0.4432072114770645